### ISSUE TITLE
How to create a type union from code

### ISSUE THREAD

**Issue by vabatta** [yellicode/typescript-extension#1]
Hi,

how should I write my code to generate such a type:
```ts
export type MyReactComponent = FunctionComponent<MyProps<any>> | ComponentClass<MyProps<any>>;
```

Poking around, I found that there is a `ts.writeStringLiteralType()` but it requires a `elements.Enumeration` which I have no idea on how to create from code.

**Comment by mdelaat** [comment]
You are right, there is no method dedicated to writing union types apart from string literals (yet). But I think the easiest way would be (depending on what your variables are):
```ts
const componentName = 'MyReactComponent';        
ts.writeLine(`export type ${componentName} = FunctionComponent<MyProps<any>> | ComponentClass<MyProps<any>>;`);`
```
